version: "3.8"

services:
    web:
        build: ./flask_app
        ports:
            - "5000:5000"
        environment:
            - REDIS_URL=redis://redis:6379
            - POSTGRES_HOST=postgres
            - POSTGRES_DB=flask_db
            - POSTGRES_USER=flask_user
            - POSTGRES_PASSWORD=flask_password
        depends_on:
            - redis
            - postgres

    redis:
        image: "redis:alpine"
        ports:
            - "6379:6379"

    postgres:
        image: "postgres:13-alpine"
        environment:
            POSTGRES_DB: flask_db
            POSTGRES_USER: flask_user
            POSTGRES_PASSWORD: flask_password
        ports:
            - "5432:5432"
